Sounds:
  Gui_Open_Sound: "BLOCK_CHEST_OPEN-1-1"
  Receipt_Reward_Sound: "ENTITY_PLAYER_LEVELUP-1-1"
  Not_Receipt_Reward_Sound: "ENTITY_VILLAGER_NO-1-1"
  Already_Received_Reward_Sound: "ENTITY_VILLAGER_NO-1-1"
Messages:
  Not_Receipt_Reward_Message: "&e[알림] &f아직 %rewards% &f을 수령할 수 없습니다!"
  Already_Received_Reward_Message: "&e[알림] %rewards% &f을 이미 수령하셨습니다!"
  Receipt_Reward_Message: "&e[알림] %rewards% &f을 수령했습니다!"
  Not_Receipt_Reward_Lore: "&e아직 해당 일차보상을 획득할 수 없습니다."
  Already_Received_Reward_Lore: "&e이미 해당 일차보상을 수령했습니다."
  Receive_Reward_Lore: "&e해당 일차보상을 수령할 수 있습니다."



