name: Dailyreward
version: '${project.version}'
main: net.teamuni.dailyreward.Dailyreward
api-version: 1.18
commands:
  출석체크:
    permission: dailyreward.opengui
permissions:
  dailyreward.opengui:
    default: true
  dailyreward.reload:
    default: op

